# Global Config
sudo: required

services:
  - docker

# Docker run will build everything we need.
build: ""

jobs:
  include:
    - stage: "API"
      script:
        - docker-compose run --rm pdf flake8
        - docker-compose run --rm pdf pytest -vv
